import type { BundledAgent, AgentManifest } from './types.js';

export const BUNDLED_AGENTS: BundledAgent[] = [
  {
    id: 'architect',
    name: 'Architect',
    description: 'Software architecture specialist for system design, scalability, and technical decision-making',
    category: 'planning',
    model: 'opus',
    tools: ['Read', 'Grep', 'Glob'],
    tags: ['architecture', 'design', 'planning', 'scalability'],
    version: '1.0.0',
  },
  {
    id: 'build-error-resolver',
    name: 'Build Error Resolver',
    description: 'Build and TypeScript error resolution specialist. Fixes build/type errors with minimal diffs',
    category: 'development',
    model: 'sonnet',
    tools: ['Read', 'Write', 'Edit', 'Bash', 'Grep', 'Glob'],
    tags: ['build', 'typescript', 'errors', 'debugging'],
    version: '1.0.0',
  },
  {
    id: 'code-reviewer',
    name: 'Code Reviewer',
    description: 'Expert code review specialist. Reviews code for quality, security, and maintainability',
    category: 'review',
    model: 'sonnet',
    tools: ['Read', 'Grep', 'Glob', 'Bash'],
    tags: ['review', 'quality', 'best-practices'],
    version: '1.0.0',
  },
  {
    id: 'doc-updater',
    name: 'Documentation Updater',
    description: 'Documentation and codemap specialist. Updates codemaps, READMEs, and guides',
    category: 'documentation',
    model: 'sonnet',
    tools: ['Read', 'Write', 'Edit', 'Bash', 'Grep', 'Glob'],
    tags: ['documentation', 'readme', 'guides'],
    version: '1.0.0',
  },
  {
    id: 'e2e-runner',
    name: 'E2E Test Runner',
    description: 'End-to-end testing specialist using Playwright. Generates, maintains, and runs E2E tests',
    category: 'testing',
    model: 'sonnet',
    tools: ['Read', 'Write', 'Edit', 'Bash', 'Grep', 'Glob'],
    tags: ['testing', 'e2e', 'playwright', 'automation'],
    version: '1.0.0',
  },
  {
    id: 'planner',
    name: 'Implementation Planner',
    description: 'Expert planning specialist for complex features and refactoring. Creates step-by-step plans',
    category: 'planning',
    model: 'opus',
    tools: ['Read', 'Grep', 'Glob'],
    tags: ['planning', 'design', 'architecture'],
    version: '1.0.0',
  },
  {
    id: 'refactor-cleaner',
    name: 'Refactor & Clean',
    description: 'Dead code cleanup and consolidation specialist. Removes unused code and duplicates',
    category: 'refactoring',
    model: 'sonnet',
    tools: ['Read', 'Write', 'Edit', 'Bash', 'Grep', 'Glob'],
    tags: ['refactoring', 'cleanup', 'dead-code'],
    version: '1.0.0',
  },
  {
    id: 'security-reviewer',
    name: 'Security Reviewer',
    description: 'Security vulnerability detection and remediation specialist. OWASP Top 10, secrets, injection',
    category: 'security',
    model: 'opus',
    tools: ['Read', 'Write', 'Edit', 'Bash', 'Grep', 'Glob'],
    tags: ['security', 'vulnerabilities', 'owasp', 'audit'],
    version: '1.0.0',
  },
  {
    id: 'tdd-guide',
    name: 'TDD Guide',
    description: 'Test-Driven Development specialist. Write tests first, then implement minimal code to pass',
    category: 'testing',
    model: 'sonnet',
    tools: ['Read', 'Write', 'Edit', 'Bash', 'Grep'],
    tags: ['testing', 'tdd', 'unit-tests', 'coverage'],
    version: '1.0.0',
  },
];

export const AGENT_MANIFEST: AgentManifest = {
  version: 1,
  agents: BUNDLED_AGENTS,
};
