import type { HookTemplate, HookTemplateManifest } from './types.js';

export const HOOK_TEMPLATES: HookTemplate[] = [
  {
    id: 'typescript-check',
    name: 'TypeScript Type Check',
    description: 'Run TypeScript type checking before commits',
    category: 'quality',
    event: 'commit:pre',
    command: 'npx tsc --noEmit',
    timeout: 60000,
    blocking: true,
  },
  {
    id: 'eslint-check',
    name: 'ESLint Check',
    description: 'Run ESLint on staged files before commits',
    category: 'quality',
    event: 'commit:pre',
    command: 'files=$(git diff --cached --name-only --diff-filter=d | grep -E "\\.(js|ts|jsx|tsx)$"); [ -z "$files" ] || npx eslint --fix $files',
    timeout: 60000,
    blocking: true,
  },
  {
    id: 'prettier-format',
    name: 'Prettier Format',
    description: 'Format staged files with Prettier before commits',
    category: 'quality',
    event: 'commit:pre',
    command: 'npx prettier --write $(git diff --cached --name-only --diff-filter=d)',
    timeout: 30000,
    blocking: false,
  },
  {
    id: 'test-on-save',
    name: 'Run Tests on Save',
    description: 'Run related tests when test files are saved',
    category: 'quality',
    event: 'file:save',
    matcher: '**/*.test.{ts,tsx,js,jsx}',
    command: 'npx vitest run {{file}}',
    timeout: 120000,
    blocking: false,
  },
  {
    id: 'security-scan',
    name: 'Security Scan',
    description: 'Scan for security vulnerabilities before commits',
    category: 'security',
    event: 'commit:pre',
    command: 'npm audit --audit-level=high',
    timeout: 60000,
    blocking: true,
  },
  {
    id: 'secret-detection',
    name: 'Secret Detection',
    description: 'Detect secrets in staged files before commits',
    category: 'security',
    event: 'commit:pre',
    command: 'files=$(git diff --cached --name-only --diff-filter=d); [ -z "$files" ] || npx secretlint $files',
    timeout: 30000,
    blocking: true,
  },
  {
    id: 'build-check',
    name: 'Build Check',
    description: 'Verify build succeeds before commits',
    category: 'quality',
    event: 'commit:pre',
    command: 'npm run build',
    timeout: 300000,
    blocking: true,
  },
  {
    id: 'session-summary',
    name: 'Session Summary',
    description: 'Generate session summary on session end',
    category: 'productivity',
    event: 'session:end',
    command: 'echo "Session ended at $(date)" >> ~/.skillkit/sessions/$(date +%Y-%m-%d).log',
    timeout: 5000,
    blocking: false,
  },
  {
    id: 'auto-commit-message',
    name: 'Auto Commit Message',
    description: 'Generate conventional commit message',
    category: 'workflow',
    event: 'commit:pre',
    command: 'git diff --cached --stat',
    timeout: 5000,
    blocking: false,
  },
  {
    id: 'notify-build-fail',
    name: 'Build Failure Notification',
    description: 'Notify on build failure',
    category: 'workflow',
    event: 'build:fail',
    command: 'echo "Build failed at $(date)" | tee -a ~/.skillkit/build.log',
    timeout: 5000,
    blocking: false,
  },
  {
    id: 'test-coverage-check',
    name: 'Test Coverage Check',
    description: 'Verify test coverage meets threshold before commits',
    category: 'quality',
    event: 'commit:pre',
    command: 'npm test -- --coverage --coverageThreshold=\'{"global":{"statements":80}}\'',
    timeout: 180000,
    blocking: true,
  },
  {
    id: 'dependency-check',
    name: 'Dependency Check',
    description: 'Check for outdated dependencies on session start',
    category: 'productivity',
    event: 'session:start',
    command: 'npm outdated || true',
    timeout: 30000,
    blocking: false,
  },
];

export const HOOK_TEMPLATE_MANIFEST: HookTemplateManifest = {
  version: 1,
  templates: HOOK_TEMPLATES,
};
