import { type SecurityRule, Severity, ThreatCategory } from '../types.js';

export const commandInjectionRules: SecurityRule[] = [
  {
    id: 'CI001',
    category: ThreatCategory.COMMAND_INJECTION,
    severity: Severity.CRITICAL,
    patterns: [/\beval\s*\(/],
    excludePatterns: [/\/\/.*\beval\b/, /#.*\beval\b/, /['"].*\beval\b.*['"]/],
    fileTypes: ['typescript', 'javascript', 'python'],
    description: 'eval() call: dynamic code execution',
    remediation: 'Replace eval() with safer alternatives like JSON.parse() or dedicated parsers.',
  },
  {
    id: 'CI002',
    category: ThreatCategory.COMMAND_INJECTION,
    severity: Severity.CRITICAL,
    patterns: [/new\s+Function\s*\(/, /\bFunction\s*\(\s*['"`]/],
    fileTypes: ['typescript', 'javascript'],
    description: 'Function() constructor: dynamic code generation',
    remediation: 'Avoid Function() constructor. Use static code structures.',
  },
  {
    id: 'CI003',
    category: ThreatCategory.COMMAND_INJECTION,
    severity: Severity.CRITICAL,
    patterns: [
      /child_process\s*['"]?\s*\)\s*\.\s*exec\s*\(/,
      /\bexec\s*\(\s*['"`].*\$\{/,
      /\bexecSync\s*\(/,
      /require\s*\(\s*['"]child_process['"]\s*\)/,
    ],
    fileTypes: ['typescript', 'javascript'],
    description: 'child_process execution: shell command injection risk',
    remediation: 'Use execFile() with argument arrays instead of exec() with string interpolation.',
  },
  {
    id: 'CI004',
    category: ThreatCategory.COMMAND_INJECTION,
    severity: Severity.CRITICAL,
    patterns: [
      /subprocess\.(?:call|run|Popen)\s*\([^)]*shell\s*=\s*True/,
      /os\.system\s*\(/,
      /os\.popen\s*\(/,
    ],
    fileTypes: ['python'],
    description: 'Python shell execution with shell=True or os.system()',
    remediation: 'Use subprocess.run() with shell=False and argument lists.',
  },
  {
    id: 'CI005',
    category: ThreatCategory.COMMAND_INJECTION,
    severity: Severity.MEDIUM,
    patterns: [/`[^`]*\$\{[^}]*\}[^`]*`/],
    excludePatterns: [/console\.log/, /logger\./, /throw\s+new/, /return\s+`/, /=\s*`/, /\+\s*`/, /\(\s*`/],
    fileTypes: ['typescript', 'javascript'],
    description: 'Template literal with dynamic content in potential command context',
    remediation: 'Avoid interpolating user input into command strings. Use argument arrays.',
  },
  {
    id: 'CI006',
    category: ThreatCategory.COMMAND_INJECTION,
    severity: Severity.MEDIUM,
    patterns: [/\.\.\//, /\.\.\\/],
    excludePatterns: [/import\s+.*from\s+['"]\.\.\//, /require\s*\(\s*['"]\.\.\//, /\/\/.*\.\.\//, /#.*\.\.\//, /\]\(\.\.\//, /href\s*=\s*['"]\.\.\//, /src\s*=\s*['"]\.\.\//, /include\s+['"]\.\.\//, /!\[.*\]\(\.\.\//, /\.\.\/node_modules/],
    fileTypes: ['typescript', 'javascript', 'python', 'bash'],
    description: 'Path traversal: relative path escaping directory boundaries',
    remediation: 'Use path.resolve() and validate paths are within expected directories.',
  },
  {
    id: 'CI007',
    category: ThreatCategory.COMMAND_INJECTION,
    severity: Severity.HIGH,
    patterns: [
      /;\s*(?:rm|cat|curl|wget|nc|ncat)\s+/,
      /\|\s*(?:sh|bash|zsh|dash)\b/,
      /&&\s*(?:rm|curl|wget)\s+/,
    ],
    fileTypes: ['bash', 'markdown'],
    description: 'Shell command chaining with dangerous commands',
    remediation: 'Avoid chaining shell commands. Use discrete, validated command invocations.',
  },
  {
    id: 'CI008',
    category: ThreatCategory.COMMAND_INJECTION,
    severity: Severity.MEDIUM,
    patterns: [/\bexec\s*\(/, /\bspawn\s*\(/],
    excludePatterns: [/execFile\s*\(/, /\.exec\s*\(/, /RegExp.*\.exec/],
    fileTypes: ['typescript', 'javascript'],
    description: 'Process execution functions detected',
    remediation: 'Prefer execFile() over exec(). Validate all command arguments.',
  },
  {
    id: 'CI009',
    category: ThreatCategory.COMMAND_INJECTION,
    severity: Severity.HIGH,
    patterns: [
      /\b__import__\s*\(/,
      /\bcompile\s*\(\s*['"][^'"]*['"]\s*,\s*['"][^'"]*['"]\s*,\s*['"]exec['"]\s*\)/,
    ],
    fileTypes: ['python'],
    description: 'Python dynamic import or code compilation',
    remediation: 'Use standard import statements. Avoid dynamic code compilation.',
  },
  {
    id: 'CI010',
    category: ThreatCategory.COMMAND_INJECTION,
    severity: Severity.MEDIUM,
    patterns: [/\bvm\.runIn(?:ThisContext|NewContext|Context)\s*\(/],
    fileTypes: ['typescript', 'javascript'],
    description: 'Node.js vm module: sandboxed but potentially dangerous code execution',
    remediation: 'Avoid vm module for untrusted code. Use proper sandboxing solutions.',
  },
];
