import { type SecurityRule, Severity, ThreatCategory } from '../types.js';

export const promptInjectionRules: SecurityRule[] = [
  {
    id: 'PI001',
    category: ThreatCategory.PROMPT_INJECTION,
    severity: Severity.CRITICAL,
    patterns: [/ignore\s+(all\s+)?(previous|above|prior)\s+(instructions?|rules?|guidelines?)/i],
    description: 'Instruction override: attempts to discard system instructions',
    remediation: 'Remove instruction override language. Skills should not attempt to modify agent behavior.',
  },
  {
    id: 'PI002',
    category: ThreatCategory.PROMPT_INJECTION,
    severity: Severity.CRITICAL,
    patterns: [/forget\s+(everything|all|what)\s+(you|i)\s+(told|said|learned)/i],
    description: 'Context clearing: attempts to wipe agent memory',
    remediation: 'Remove context-clearing instructions.',
  },
  {
    id: 'PI003',
    category: ThreatCategory.PROMPT_INJECTION,
    severity: Severity.CRITICAL,
    patterns: [/disregard\s+(your|all|the)\s+(training|programming|instructions?)/i],
    description: 'Training bypass: attempts to override agent training',
    remediation: 'Remove training bypass instructions.',
  },
  {
    id: 'PI004',
    category: ThreatCategory.PROMPT_INJECTION,
    severity: Severity.CRITICAL,
    patterns: [/new\s+instructions?:\s*$/im, /system\s+prompt:\s*$/im],
    description: 'System prompt injection: attempts to inject new system-level instructions',
    remediation: 'Do not include system prompt markers in skill content.',
  },
  {
    id: 'PI005',
    category: ThreatCategory.PROMPT_INJECTION,
    severity: Severity.HIGH,
    patterns: [/you\s+are\s+(now|actually|really)\s+(a|an|the)/i],
    description: 'Role manipulation: attempts to reassign agent identity',
    remediation: 'Skills should not attempt to change the agent\'s role or identity.',
  },
  {
    id: 'PI006',
    category: ThreatCategory.PROMPT_INJECTION,
    severity: Severity.HIGH,
    patterns: [/pretend\s+(to\s+be|you\s+are)/i, /act\s+as\s+(if|though)\s+you/i],
    description: 'Roleplay manipulation: attempts to alter agent behavior via pretense',
    remediation: 'Remove roleplay instructions that change agent behavior.',
  },
  {
    id: 'PI007',
    category: ThreatCategory.PROMPT_INJECTION,
    severity: Severity.HIGH,
    patterns: [/from\s+now\s+on,?\s+(you|always|never)/i],
    description: 'Persistent behavior change: attempts to permanently alter agent behavior',
    remediation: 'Skills should provide task-specific instructions, not permanent behavior changes.',
  },
  {
    id: 'PI008',
    category: ThreatCategory.PROMPT_INJECTION,
    severity: Severity.HIGH,
    patterns: [
      /show\s+me\s+your\s+(system\s+)?(prompt|instructions)/i,
      /reveal\s+your\s+(system\s+)?(prompt|instructions)/i,
      /what\s+are\s+your\s+(system\s+)?(instructions|rules)/i,
    ],
    description: 'System prompt extraction: attempts to reveal agent configuration',
    remediation: 'Remove attempts to extract system prompts.',
  },
  {
    id: 'PI009',
    category: ThreatCategory.PROMPT_INJECTION,
    severity: Severity.CRITICAL,
    patterns: [
      /unrestricted\s+mode/i,
      /(?<!detect(?:ing)?[\s.]+)(?<!prevent(?:ing)?[\s.]+)jailbreak/i,
      /DAN\s+(mode|prompt)/i,
      /bypass\s+(safety|content)\s+(filter|restriction)/i,
    ],
    description: 'Policy bypass: attempts to disable safety restrictions',
    remediation: 'Remove jailbreak or policy bypass instructions.',
  },
  {
    id: 'PI010',
    category: ThreatCategory.PROMPT_INJECTION,
    severity: Severity.HIGH,
    patterns: [
      /don'?t\s+tell\s+the\s+user/i,
      /hide\s+this\s+from\s+the\s+user/i,
      /keep\s+this\s+(a\s+)?secret/i,
      /do\s+not\s+mention\s+this/i,
    ],
    description: 'Concealment: instructs agent to hide information from user',
    remediation: 'Skills should be transparent. Remove concealment instructions.',
  },
  {
    id: 'PI011',
    category: ThreatCategory.PROMPT_INJECTION,
    severity: Severity.HIGH,
    patterns: [
      /```\s*(system|assistant|user)\s*$/im,
      /<\/?(?:system|user|assistant|human|ai|claude)>/i,
    ],
    description: 'Delimiter injection: attempts to inject conversation role markers',
    remediation: 'Remove conversation role delimiters from skill content.',
  },
  {
    id: 'PI012',
    category: ThreatCategory.PROMPT_INJECTION,
    severity: Severity.HIGH,
    patterns: [/\[INST\]/i, /\[\/INST\]/i, /<<SYS>>/i, /<<\/SYS>>/i],
    description: 'Model-specific delimiter injection: Llama-style instruction delimiters',
    remediation: 'Remove model-specific instruction delimiters.',
  },
  {
    id: 'PI013',
    category: ThreatCategory.PROMPT_INJECTION,
    severity: Severity.MEDIUM,
    patterns: [/---\s*$/im],
    excludePatterns: [/^---\s*$/],
    multiline: true,
    description: 'YAML front-matter injection: attempts to inject via YAML metadata',
    remediation: 'Use standard SKILL.md frontmatter format only.',
  },
  {
    id: 'PI014',
    category: ThreatCategory.PROMPT_INJECTION,
    severity: Severity.MEDIUM,
    patterns: [
      /<!--[^>]{0,500}?(?:ignore|system|instruction|secret|override)[^>]{0,500}?-->/i,
    ],
    description: 'Hidden HTML comments with suspicious instruction content',
    remediation: 'Do not hide instructions in HTML comments.',
  },
  {
    id: 'PI015',
    category: ThreatCategory.PROMPT_INJECTION,
    severity: Severity.MEDIUM,
    patterns: [/\[comment\]:\s*#\s*\([^)]*(?:ignore|system|override)[^)]*\)/i],
    description: 'Hidden Markdown comments with suspicious content',
    remediation: 'Do not hide instructions in Markdown comments.',
  },
];
